# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0206c1b410f3bf6dc0a230776a9e5cf6633c2b0a0885d65246c361ba613d3451097a285d5ad673f1d7cf871c86fd4cc5c2598b18b3af6d13a333d9b162b18abd

test:
  secret_key_base: dabb6e14fe2722343e17cb82ae13d6d5866b16d31a2c6f36121541f8b363db92f50c143dbbe1e4d34fac1c960acd95f0fa8bf6a6cee6421ef65306e0de130c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
